version: '3.9'
services:
  api:
    build: ./api/code
    hostname: api 
    volumes: 
      - ./api/code:/app
    environment:
      - CONSUMER_PORT=${CONSUMER_PORT}
      - CONSUMER_ENDPOINT=${CONSUMER_ENDPOINT}
    ports:
      - "5000:5000"
  consumer:
    build: ./consumer/code
    hostname: consumer
    volumes:
      - ./consumer/code:/app
    environment:
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - API_ENDPOINT=${API_ENDPOINT}
      - CONSUMER_PORT=${CONSUMER_PORT}
      - CONSUMER_ENDPOINT=${CONSUMER_ENDPOINT}
    ports:
      - "80:80"